#header
name: ERIC HUANG
description: Passionate Web Developer.
favicon: /img/favicon.png
ga: 'UA-79167899-1'

#nav
nav:
    ARCHIVE: /
    GALLERY:  /gallery/
    ABOUT: /about/

#post
excerpt_link: Continue Reading

github: https://github.com/ele828
weibo: http://weibo.com/ele828
linkedin: http://cn.linkedin.com/in/ele828/en

#copyright
themeLink: https://github.com/yiliashaw/hexo-theme-prince